---
title: "Caveats"
---

\  

Users of the data presented on this site need to be aware of the following important caveats: 

1. The usefulness of various indicators to tracking the pandemic has evolved rapidly. Most notably, while case counts were always under-reports, they were still useful given the widespread availability of PCR testing in Canada. Due to changing policies and eligibility restrictions for testing, this is no longer the case. This site still includes these data, but it must be recognized that they do not accurately represent pandemic trends. Two years into the pandemic, the most useful indicators for tracking the pandemic are likely hospitalizations, deaths, test positivity, and wastewater Covid-19 signals. (Wastewater data are not included on this site.)

2. While I strive to include the most recent and complete available data, there is no guarantee of data accuracy. I am aggregating what official sources have been reporting over time. I do try to correct obvious data input error in the local data, but I have not implemented an automatic error detection process.

3. At the municipal and RLS levels, official data do not report numbers of less than 6 precisely, for good privacy reasons. When "5 or less" are reported, I record this as 5 cases. Users must be aware that counts of 5 do not precisely reflect the actual situation at those levels, but refer to 1-5 cases.

4. Expressing vaccination doses as a percentage of the Outaouais population assumed that receivers of the vaccine are Outaouais residents **and** that they had received one dose only. These strong assumptions were reasonable early in the vaccination campaign, but less so as time progressed. Therefore, I stopped including this information.

Further, the CISSS Outaouais (local, municipal) data are subject to the following caveats:

5. The date and time in the dataset refer to when the CISSS Outaouais page was accessed, not when cases occurred.

6. The local trend data are not complete (i.e daily) for several reasons. First, due to a syncing glitch, I lost some HTML source files. Second, the CISSS Outaouais site is not updated every day. Third, the automatic downloads have not happened every day, either because my computer was turned off, or because my software for scheduling scripts has failed a few times. Since the snapshots include cumulative counts, this is not necessarily a problem, but it means that changes in local case counts cannot always be precisely dated. In the figures of these local data, "rugs" indicate dates for which the data are available.
