---
title: "Covid19 Situation in Outaouais"
params: 
  optimize: true
---

```{r setup, include=FALSE}
source("_R/setup.R")
source("_R/figures_theme.R")
source("_R/CovidFig.R")
load("_data/cisss_daily.RData")
load("_data/hospitalization.RData")
load("_data/inspq.RData")
load("_data/vaccination.RData")
vaccination <- vaccination %>% 
  mutate(date = lubridate::as_date(vaccination$time)) %>% 
  group_by(key, date) %>% filter(time == max(time)) 
pop_outaouais_2020 <- 401388
```

## {.tabset .tabset-fade .tabset-pills}

```{r cases_avg}
knitr::asis_output("### New cases")
RegionFig(df = inspq[inspq$key == "Average increase per day", ], 
          bars = inspq[inspq$key == "New cases", ], 
          pop = "per100k",
          caption = "Data source: www.inspq.qc.ca/sites/default/files/covid/donnees/covid19-hist.csv")
```

```{r cases_active}
knitr::asis_output("### Active cases")
RegionFig(df = inspq[inspq$key %in% c("Active cases"), ], 
          pop = "per100k", 
          caption = "Data source: www.inspq.qc.ca/sites/default/files/covid/donnees/covid19-hist.csv")
```


```{r cases_cumulative}
knitr::asis_output("### Cumulative cases")
RegionFig(df = inspq[inspq$key %in% c("Total cases", "Total recovered cases"), ], 
          caption = "Data source: www.inspq.qc.ca/sites/default/files/covid/donnees/covid19-hist.csv")
```

```{r testing}
knitr::asis_output("### Daily tests")
RegionFig(df = inspq[inspq$key %in% c("Average testing per day"), ],
          bars = inspq[inspq$key %in% c("Persons tested"), ],
          caption = "Data source: www.inspq.qc.ca/sites/default/files/covid/donnees/covid19-hist.csv")
```

```{r positive, eval = FALSE}
knitr::asis_output("### Positive tests")
RegionFig(df = inspq[inspq$key %in% c("Average positive tests per day"), ], 
          bars = inspq[inspq$key %in% c("Persons tested positive"), ],
          caption = "Data source: www.inspq.qc.ca/sites/default/files/covid/donnees/covid19-hist.csv")
```

```{r positivity}
knitr::asis_output("### Test positivity")
RegionFig(df = inspq[inspq$key %in% c("Average test positivity (%)"), ], 
          bars = inspq[inspq$key %in% c("Test positivity (%)"), ], 
          caption = "Data source: www.inspq.qc.ca/sites/default/files/covid/donnees/covid19-hist.csv")
```

```{r cases_deaths}
knitr::asis_output("### Deaths")
RegionFig(df = inspq[inspq$key %in% c("Total deaths", "Total deaths (CHSLD)", "Total deaths (RPA)", "Total deaths (home & unknown)", "Total deaths (other)"), ], 
          caption = "Data source: www.inspq.qc.ca/sites/default/files/covid/donnees/covid19-hist.csv")
```

```{r hospitalization}
knitr::asis_output("### Hospitalizations")
RegionFig(second = hospitalization[hospitalization$key %in% c("Active hospitalizations, non-ICU", "Active hospitalizations, ICU"), ],
          df = inspq[inspq$key %in% c("New hospitalizations"), ], 
          caption = "Data source: www.inspq.qc.ca/sites/default/files/covid/donnees/covid19-hist.csv &\n www.donneesquebec.ca/recherche/dataset/covid-19-portrait-quotidien-des-hospitalisations")
```

```{r hospitalizations}
knitr::asis_output("### Total hospitalizations")
RegionFig(df = inspq[inspq$key %in% c("Total hospitalizations, non-ICU", "Total hospitalizations, ICU", "Total hospitalizations"), ], 
          caption = "Data source: www.inspq.qc.ca/sites/default/files/covid/donnees/covid19-hist.csv")
```

```{r vaccinations}
knitr::asis_output("### Vaccinations")
### RegionFig(df = vaccination, caption = "Data source: www.quebec.ca/en/health/health-issues/a-z/2019-coronavirus/situation-coronavirus-in-quebec/covid-19-vaccination-data/")
RegionFig(df = inspq[inspq$key %in% c("Vaccine doses administered"), ], 
          # pop = "percent", 
          dlabels = "%d %b %Y",
          caption = "Data source: www.inspq.qc.ca/sites/default/files/covid/donnees/covid19-hist.csv")
```

```{r vaccinations_total}
knitr::asis_output("### Total vaccinations")
RegionFig(df = inspq[inspq$key %in% c("Total vaccine doses administered"), ], 
          dlabels = "%d %b %Y",
          caption = "Data source: www.inspq.qc.ca/sites/default/files/covid/donnees/covid19-hist.csv")
```

```{r opencovid}
knitr::asis_output("### Outaouais & Ottawa (opencovid.ca)")
RegionFig(df = daily[daily$key %in% c("Average increase per day (Outaouais)", "Average increase per day (Ottawa)") & daily$table == "opencovid.ca", ],
          caption = "Data source: opencovid.ca/api/")
```

##

Last data update: `r str_replace(read_file("_data/data_update_time.txt"), "\n", "")`
