---
title: "Average increase by RLS "
params: 
  optimize: false
---

```{r setup, include=FALSE}
source("_R/setup.R")
source("_R/functions_figures.R")
load("_data/cisss.RData")
load("_data/cisss_daily.RData")
load("_data/hospitalization.RData")
load("_data/inspq.RData")
load("_data/rls.RData")
load("_data/vaccination.RData")
vaccination <- vaccination %>% 
  mutate(date = lubridate::as_date(vaccination$time)) %>% 
  group_by(key, date) %>% filter(time == max(time)) 
pop_outaouais_2020 <- 401388
```

## {.tabset .tabset-fade .tabset-pills}

### Gatineau & Outaouais
```{r rls_avg_gatineau}
LocalFig(df = rls[rls$key %in% c("Average increase per day (Outaouais)", "Active cases (Outaouais)", "RLS de Grande-Rivière - Hull - Gatineau") & rls$table == "average", ], 
       rug = FALSE, 
       note_last_day = FALSE,
       caption = "Data source: www.inspq.qc.ca/sites/default/files/covid/donnees/tableau-rls-new.csv")
```

### Collines
```{r rls_avg_collines}
LocalFig(df = rls[rls$key == "RLS des Collines-de-l'Outaouais" & rls$table == "average", ], 
       rug = FALSE, 
       note_last_day = FALSE,
       caption = "Data source: www.inspq.qc.ca/sites/default/files/covid/donnees/tableau-rls-new.csv")
```

### Pontiac
```{r rls_avg_pontiac}
LocalFig(df = rls[rls$key == "RLS du Pontiac" & rls$table == "average", ], 
       rug = FALSE, 
       note_last_day = FALSE,
       caption = "Data source: www.inspq.qc.ca/sites/default/files/covid/donnees/tableau-rls-new.csv")
```

### Papineau
```{r rls_avg_papineau}
LocalFig(df = rls[rls$key == "RLS de la Vallée-de-la-Lièvre et de la Petite Nation" & rls$table == "average", ], 
       rug = FALSE, 
       note_last_day = FALSE,
       caption = "Data source: www.inspq.qc.ca/sites/default/files/covid/donnees/tableau-rls-new.csv")
```

### Vallée
```{r rls_avg_vallee}
LocalFig(df = rls[rls$key == "RLS de la Vallée-de-la-Gatineau" & rls$table == "average", ], 
       rug = FALSE, 
       note_last_day = FALSE,
       caption = "Data source: www.inspq.qc.ca/sites/default/files/covid/donnees/tableau-rls-new.csv")
```

```{r rls_cumulative, eval = FALSE}
LocalFig(df = rls[rls$key %in% c("Total cases (Outaouais)", "RLS de Grande-Rivière - Hull - Gatineau", "RLS des Collines-de-l'Outaouais", "RLS du Pontiac", "RLS de la Vallée-de-la-Lièvre et de la Petite Nation", "RLS de la Vallée-de-la-Gatineau") & rls$table == "cases", ], 
       rug = FALSE, 
       note_last_day = FALSE,
       caption = "Data source: www.inspq.qc.ca/sites/default/files/covid/donnees/tableau-rls-new.csv")
```

##

Last data update: `r str_replace(read_file("_data/data_update_time.txt"), "\n", "")`
