---
title: "Covid19 Situation in Outaouais Schools"
output:
  html_document:
    theme: darkly
    toc: true
    toc_depth: 1
    includes:
      before_body: html/translate.html
params: 
  optimize: false
---

```{r setup, include=FALSE}
library(tidyverse)
library(lubridate)
knitr::knit_hooks$set(optipng = knitr::hook_optipng)
knitr::knit_hooks$set(pngquant = knitr::hook_pngquant)
knitr::opts_chunk$set(echo = FALSE, cache = FALSE, 
                      results = 'hide', warning = FALSE, message = FALSE)
knitr::opts_chunk$set(dpi = 120, fig.width = 7, fig.height = 5, 
                      out.width = "100%", out.height = "100%")
if(params$optimize) knitr::opts_chunk$set(optipng = '-o7')
Sys.setlocale(category = "LC_ALL", locale = "en_CA.UTF-8")
```

```{r data}
# load("data/municipalities.RData")
# pop_outaouais_2020 <- 401388
load("data/schools.RData")
# tapply(schools$school, schools$admin, function(x) length(unique(x)))
# table(schools[, c("note", "color_code")])
# unique(schools$school)
schools$school <- str_replace(schools$school, 
  "École Cité Étudiante de la Haute-Gatineau", 
  "École Cité Étudiante\nde la Haute-Gatineau")
schools$school <- str_replace(schools$school, 
  "École Cœur de la Gatineau, pavillon St-Nom-de-Marie", 
  "École Cœur de la Gatineau, pavillon St-Nom-de-Marie")
schools$school <- str_replace(schools$school, 
  "Centre d'éducation des Adultes, programme FIS maison amitié de Maniwaki", 
  "Centre d'éducation des Adultes,\nprogramme FIS maison\namitié de Maniwaki")
schools$school <- str_replace(schools$school, "École", "É.")
schools$school <- str_replace(schools$school, "école", "É.")
schools$school <- str_replace(schools$school, "School", "S.")
schools$school <- str_replace(schools$school, "Shcool", "S.")
schools$school <- str_replace(schools$school, "Education", "Ed.")
schools$school <- str_replace(schools$school, 
                              "Centre de formation professionnelle des métiers", 
                              "CFP")
schools$school <- str_replace(schools$school, 
                              "Centre de formation professionnelle", 
                              "CFP")
schools$school <- str_replace(schools$school, "Centre", "C.")
schools$school <- str_replace(schools$school, " de l'Outaouais", "\nde l'Outaouais")
schools$school <- str_replace(schools$school, "Collège ", "Collège\n")
schools$school <- str_replace(schools$school, ", pavillon ", ", ")
board <- "Centre de services scolaire des Hauts-Bois-de-l'Outaouais"
schools$school[schools$admin == board] <- 
  str_replace(schools$school[schools$admin == board], fixed(", "), ",\n")
schools$school <- str_replace(schools$school, fixed(" ("), "\n(")
schools$school <- str_trim(schools$school)
# unique(schools$school[str_detect(schools$school, "blah")])
source("functions_figures.R")
```

```{r, child = 'md/schools_intro.md', eval = FALSE}
```

# Schools with confirmed cases {.tabset .tabset-fade .tabset-pills}

## CSS des Draveurs
```{r draveurs}
SchoolsFig(c("Centre de services scolaire des Draveurs"))
```

## CSS des Portages-de-l'Outaouais
```{r portages}
SchoolsFig(c("Centre de services scolaire des Portages-de-l'Outaouais"))
```

## Western Québec School Board
```{r anglo}
SchoolsFig(c("Commission scolaire Western Québec"))
```

## CSS au Cœur-des-Vallées
```{r vallees}
SchoolsFig(c("Centre de services scolaire au Cœur-des-Vallées"))
```

## CSS des Hauts-Bois-de-l'Outaouais
```{r hauts_bois}
SchoolsFig(c("Centre de services scolaire des Hauts-Bois-de-l'Outaouais"))
```

## École privée
```{r privee}
SchoolsFig(c("École privée"))
```

# Information on this site {.tabset .tabset-pills}

```{r, child = 'md/schools_notes.md', eval = FALSE}
```

```{r, child = 'md/updates.md', eval = FALSE}
```

Last data update: `r str_replace(read_file("data/data_update_time.txt"), "\n", "")`

```{r, child = 'md/disclaimer.md', eval = FALSE}
```

```{r, child = 'md/footer.md'}
```
