---
title: "Covid19 Situation in Outaouais"
pagetitle: "covid19Outaouais"
params: 
  optimize: true
---

```{r setup, include=FALSE}
source("_R/setup.R")
source("_R/figures_theme.R")
source("_R/CovidFig.R")
load("_data/cisss.RData")
load("_data/hospitalization.RData")
load("_data/inspq.RData")
load("_data/covid19Outaouais.RData")
pop_outaouais_2020 <- 401388
```

## {.tabset .tabset-fade .tabset-pills}

### New cases
```{r cases_avg}
inspq %>% 
  filter(key == "Average increase in cases per day") %>%
  CovidFig(bars = inspq %>% filter(key == "New cases"),
         pop = "per100k",
         caption = "Data source: www.inspq.qc.ca/sites/default/files/covid/donnees/covid19-hist.csv")
```

### Active cases
```{r cases_active}
inspq %>% 
  filter(key == "Active cases") %>%
  CovidFig(pop = "per100k",
         caption = "Data source: www.inspq.qc.ca/sites/default/files/covid/donnees/covid19-hist.csv")
```

### Cumulative cases
```{r cases_cumulative}
inspq %>% 
  filter(key %in% c("Total cases", "Total recovered cases")) %>%
  CovidFig(caption = "Data source: www.inspq.qc.ca/sites/default/files/covid/donnees/covid19-hist.csv")
```

### Daily tests
```{r testing}
inspq %>% 
  filter(key == "Average testing per day") %>%
  CovidFig(bars = inspq %>% filter(key == "Persons tested"),
           caption = "Data source: www.inspq.qc.ca/sites/default/files/covid/donnees/covid19-hist.csv")
```

### Test positivity
```{r positivity}
inspq %>% 
  filter(key == "Average test positivity (%)") %>%
  CovidFig(bars = inspq %>% filter(key == "Test positivity (%)"),
           caption = "Data source: www.inspq.qc.ca/sites/default/files/covid/donnees/covid19-hist.csv")
```

### Deaths
```{r cases_deaths}
inspq %>% 
  filter(key %in% c("Total deaths", "Total deaths (CHSLD)", "Total deaths (RPA)", 
                    "Total deaths (home & unknown)", "Total deaths (other)")) %>%
  CovidFig(caption = "Data source: www.inspq.qc.ca/sites/default/files/covid/donnees/covid19-hist.csv")
```

### Hospitalizations
```{r hospitalization}
inspq %>% 
  filter(key == "New hospitalizations") %>%
  CovidFig(second = hospitalization %>% filter(key %in% c("Active hospitalizations, non-ICU", 
                                                          "Active hospitalizations, ICU")), 
           caption = "Data source: www.inspq.qc.ca/sites/default/files/covid/donnees/covid19-hist.csv &\n www.donneesquebec.ca/recherche/dataset/covid-19-portrait-quotidien-des-hospitalisations")
```

### Total hospitalizations
```{r hospitalizations}
inspq %>% 
  filter(key %in% c("Total hospitalizations, non-ICU", 
                    "Total hospitalizations, ICU", "Total hospitalizations")) %>%
  CovidFig(caption = "Data source: www.inspq.qc.ca/sites/default/files/covid/donnees/covid19-hist.csv")
```

### Vaccinations
```{r vaccinations}
inspq %>% 
  filter(key == "Vaccine doses administered") %>%
  CovidFig(dlabels = "%d %b %Y",
           caption = "Data source: www.inspq.qc.ca/sites/default/files/covid/donnees/covid19-hist.csv")
```

### Total vaccinations
```{r vaccinations_total}
inspq %>% 
  filter(key == "Total vaccine doses administered") %>%
  CovidFig(dlabels = "%d %b %Y",
           caption = "Data source: www.inspq.qc.ca/sites/default/files/covid/donnees/covid19-hist.csv")
```

### Outaouais & Ottawa (opencovid.ca)
```{r opencovid}
cisss %>% 
  filter(table == "opencovid" & key %in% c("New cases (Outaouais)", "New cases (Ottawa)")) %>%
  CovidFig(caption = "Data source: opencovid.ca/api/")
```

##

Last data update: `r str_replace(read_file("_data/data_update_time.txt"), "\n", "")`
