---
title: "Covid19 Situation in Toronto (opencovid.ca)"
output:
  html_document:
    theme: darkly
params: 
  optimize: false
---

```{r setup, include=FALSE}
library(tidyverse)
library(lubridate)
knitr::knit_hooks$set(optipng = knitr::hook_optipng)
knitr::knit_hooks$set(pngquant = knitr::hook_pngquant)
knitr::opts_chunk$set(echo = FALSE, cache = FALSE, results = 'hide', warning = FALSE)
knitr::opts_chunk$set(dpi = 120, fig.width = 7, fig.height = 5, out.width = "100%", out.height = "100%")
if(params$optimize) knitr::opts_chunk$set(optipng = '-o7')
Sys.setlocale(category = "LC_ALL", locale = "en_CA.UTF-8")
load("data/covid_local.RData")
load("data/covid_local_daily.RData")
```

```{r prep}
common_theme <- theme_classic() +
  theme(axis.text.x = element_text(angle = 15, vjust = 1.0, hjust = 1.0),
    legend.position = "bottom",
    legend.title = element_blank(),
    panel.grid.minor.x = element_line(colour="lightgray", size = 0.25))
DailyFig <- function(keys) {
  ggplot(mapping = aes(x = date, y = daily_change_avg, group = change_key, color = change_key)) +
    geom_line(data = daily[daily$change_key %in% keys & daily$table == "opencovid.ca", ]) +
    scale_x_date(date_breaks = "1 month", date_minor_breaks = "2 weeks", date_labels = "%b %Y") +
    lims(y = c(0, NA)) + labs(x = "", y = "") + common_theme
}
LocalFig <- function(keys) {
  ggplot(mapping = aes(x = time, y = value, group = key, color = key)) +
    geom_line(data = covid[covid$key %in% keys & covid$table == "opencovid.ca", ]) +
    scale_x_datetime(date_breaks = "1 month", date_minor_breaks = "2 weeks", date_labels = "%b %Y") +
    lims(y = c(0, NA)) + labs(x = "", y = "") + common_theme
}
```

## {.tabset .tabset-fade .tabset-pills}

### Average increase per day (over 7 days)
```{r opencovid_avg}
DailyFig(c("Average increase per day (Toronto)"))
```

### Cumulative cases
```{r opencovid_total}
LocalFig(c("Total cases (Toronto)"))
```

### Deaths
```{r deaths_opencovid}
LocalFig(c("Total deaths (Toronto)"))
```

##

If the figures do not show the latest data, reload this page in your web browser.

Last opencovid update: `r str_replace(read_file("data/opencovid_update_time.txt"), "\n", "")`

Last website update: `r now()`

This website is maintained by Timo Thoms.
